name: ImperioTags
version: '1.0-SNAPSHOT'
main: top.redeimperio.imperiotags.ImperioTags
api-version: 1.19
description: Plugin de tags para jogadores
depend: [PlaceholderAPI]
authors:
  - Trivalent
commands:
  tag:
    description: Comando para definir a tag do jogador
    usage: /tag <nome>
  tags:
    description: Retorna a lista de tags
    usage: /tags
  medal:
    description: Comando para definir a tag do jogador
    usage: /medal <nome>
  medals:
    description: Retorna a lista de tags
    usage: /tags
