name: ImperioRandomStuff
version: '1.0-SNAPSHOT'
main: top.redeimperio.imperiorandomstuff.ImperioRandomStuff
author: lucazof
description: Plugin com comandos básicos
commands:
  discord:
    description: Mostra o link do Discord
    usage: /discord
  regras:
    description: Mostra as regras do servidor
    usage: /regras
  aplicar:
    description: Mostra o link do formulário de aplicação da staff
    usage: /aplicar
  vip:
    description: Mostra o site para comprar VIP
    usage: /vip