name: ImperioLobby
version: '1.0-SNAPSHOT'
main: top.redeimperio.imperiolobby.ImperioLobby
api-version: 1.19
commands:
  lobby:
    description: Teleporta o jogador para o lobby
    usage: /lobby
    aliases:
      - spawn
      - hub
  setlobby:
    description: Seta o Lobby para as coordenadas do jogador
    usage: /setlobby
    aliases:
      - setspawn
      - sethub